baseurl = "https://taikii.github.io/"
title = "taikii blog"
theme = "whiteplain"
languageCode = "ja"

disqusShortname = "taikii-github-io"
googleAnalytics = "UA-108071624-1"

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2017 Taiki IKEGAME"

[params]
  dateFormat = "January 2, 2006"

[params.author]
  name = "Taiki IKEGAME"
  #gravatar = "Gravatar email"
  #avatar = "/path/to/avatar"

  # twitter = "Twitter username"
  # facebook = "Facebook username"
  # googleplus = "Googleplus username"
  # instagram = "Instagram username"
  # tumblr = "Tumblr username"
  # flickr = "Flickr username"
  # reddit = "Reddit username"
  # linkedin = "Linkedin username"
  # slideshare = "Slideshare username"
  # github = "Github username"
  # gitlab = "Gitlab username"
  # bitbucket = "Bitbucket username"
  # stackoverflow = "Stackoverflow username"
  # jsfiddle = "Jsfiddle username"
  # codepen = "Codepen username"
  # deviantart = "Deviantart username"
  # behance = "Behance username"
  # dribbble = "Dribbble username"
  # wordpress = "Wordpress username"
  # medium = "Medium username"
  # foursquare = "Foursquare username"
  # xing = "Xing username"
  # quora = "Quora username"
  # youtube = "Youtube username"
  # vimeo = "Vimeo username"
  # whatsapp = "Whatsapp username"
  # skype = "Skype username"
  # snapchat = "Snapchat username"
  # pinterest = "Pinterest username"
  # telegram = "Telegram username"
  # vine = "Vine username"
  # email = "Your email"

[taxonomies]
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 1
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 2
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 3

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
