baseurl = "https://taikii.net/"
title = "taikii blog"
theme = ["whiteplain"]
languageCode = "ja"
enableEmoji = true

#disqusShortname = ""
googleAnalytics = "UA-114764514-1"

pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"

copyright = "&copy; Copyright 2017 taikii"

[params]
  useCDN = false
  showShareIcons = true
  dateFormat = "January 2, 2006"
  favicon = "/images/favicon.ico"

[params.author]
  name = "taikii"
  gravatar = "d985cd76917351f7285c9e3eced61578"
  #avatar = "/path/to/avatar"

  twitter = "taikiix"
  # facebook = "Facebook username"
  # googleplus = "Googleplus username"
  # instagram = "Instagram username"
  # tumblr = "Tumblr username"
  # flickr = "Flickr username"
  # reddit = "Reddit username"
  # linkedin = "Linkedin username"
  # slideshare = "Slideshare username"
  github = "taikii"
  # gitlab = "Gitlab username"
  # bitbucket = "Bitbucket username"
  # stackoverflow = "Stackoverflow username"
  # jsfiddle = "Jsfiddle username"
  # codepen = "Codepen username"
  # deviantart = "Deviantart username"
  # behance = "Behance username"
  # dribbble = "Dribbble username"
  # wordpress = "Wordpress username"
  # medium = "Medium username"
  # foursquare = "Foursquare username"
  # xing = "Xing username"
  # quora = "Quora username"
  # youtube = "Youtube username"
  # vimeo = "Vimeo username"
  # whatsapp = "Whatsapp username"
  # skype = "Skype username"
  # snapchat = "Snapchat username"
  # pinterest = "Pinterest username"
  # telegram = "Telegram username"
  # vine = "Vine username"
  # email = "Your email"

[taxonomies]
  tag = "tags"
  series = "series"

# Header Menu
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 1
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 2
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 3

# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
