version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:latest
    steps:
      - checkout
      - run: git config --global user.name "Taiki IKEGAME"
      - run: git config --global user.email "taikii@users.noreply.github.com"
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: git submodule foreach git pull
      - run: git clone git@github.com:taikii/taikii.github.io.git public
      - run: hugo
      #- run:
      #    name: "Test Website"
      #    command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - deploy:
          command: cd public && git add -A . && git diff --cached --exit-code --quiet || git commit -m "Rebuilding site" && git push origin master
