version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: git config --global user.name "${GIT_USERNAME}"
      - run: git config --global user.email "${GIT_EMAIL}"
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run: git submodule foreach git pull origin main
      - run: git clone -b master ${GENERATED_SITE_REPO} public
      - run: hugo
      #- run:
      #    name: "Test Website"
      #    command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - deploy:
          command: cd public && git add -A . && git diff --cached --exit-code --quiet || git commit -m "Rebuilding site" && git push origin master
